### ISSUE TITLE
Unable to type curly and normal brackets, backslash

### ISSUE THREAD

**Issue by jdehaan** [rpwoodbu/mosh-chrome#133] opened 2016-09-28 06:48 UTC
Keyboard is german no dead keys.

Mosh 0.3.0.258
Chrome 53.0.2785.116 m
 
Nor the brackets neither any other replacement char for it is output. The problem might likely have to do with the fact that for all these characters you have to push the "Alt Gr" key in combination with another key.

**Comment by rpwoodbu** [comment] 2016-10-01 19:02
What OS are you running? I'm using Chrome OS, and am unable to reproduce this problem.

I have tried both the "German - Deutsch" and "German (Germany) - Deutsch (Deutschland)" keyboards (I don't know why Chrome OS has two that are so similar). I pressed several AltGr combinations, particularly on the number keys with the braces and brackets, and they all appeared.

I don't know what "no dead keys" means. Perhaps you're not using Chrome OS, and that's meaningful on another OS? Please try to reproduce with the Secure Shell Chrome app, as Mosh for Chrome uses their terminal emulator; if it breaks there, the problem is upstream.

Closing as unreproducable for now.

**Comment by rpwoodbu** [comment] 2016-10-01 19:12
There's an old issue which may be related: Issue #115.

**Comment by jdehaan** [comment] 2016-10-03 17:28
Thanks for checking this on your side so quickly.

The OS I have the problem on is Windows 7 Professional (fully patched)

The "no dead keys" option is useful like explained in this [example](http://superuser.com/questions/280005/how-to-make-and-non-dead-keys-on-windows-7-with-german-keyboard-layout)

I will double check if something else can be the root cause for this behaviour. I'll check especially remote control software that brings in some special keyboard shortcuts... I believe that if it would be a bug there would be much more complains. I'll report the results of my checks. I'll try the secure shell chrome app too.

**Comment by jdehaan** [comment] 2016-10-04 20:18
I double checked: the problem is there too with the Secure Shell extension. In that tool there is an option to change the Alt Gr behavior. If I change it from "auto" to "right-alt" then the problem is away.

Now the problem I have is to setup that in Mosh. The setting sticks to "null". Can you please check what is wrong with that setting in Mosh?

**Comment by rpwoodbu** [comment] 2016-10-06 01:07
Ah, very interesting. I can reproduce the bug with alt-gr-mode. It is also peculiar that it is at the top of the preferences list, in spite of ASCIIbetical ordering. I'll look into it.

**Comment by rpwoodbu** [comment] 2016-10-06 03:34
Version 0.4.1 is rolling out to dev right now. I ended up doing a big rework of the preferences page, which hopefully will avoid these kinds of issues in the future. Please put it through its paces and let me know if this fixes you (I'm almost sure it will), or if you find something that is broken.

**Comment by rpwoodbu** [comment] 2016-10-06 04:53
Aaand make that version 0.4.2, because I messed up. 😉

**Comment by jdehaan** [comment] 2016-10-07 20:51
Now I can make the settings and they are stored correctly in the GUI. So far that rocks, thanks! However no matter what I tune the effect is not the same as in using directly the ssh extension. So I suppose the setting is somehow lost on the way to ssh (the shell behaves badly exactly as before). I tried right+alt and the other settings as well. Used version is v0.4.2

**Comment by rpwoodbu** [comment] 2016-10-07 21:13
Oh crap, you're right! I know I thought to test that, and thought I did, but apparently I didn't. OK, I'll look into that this weekend. Thanks for checking!

**Closed** 2016-10-08 20:29 UTC

**Comment by rpwoodbu** [comment] 2016-10-08 20:31
OK, v0.4.3 is rolling out now. Let me know if this fixes it for you.

**Comment by jdehaan** [comment] 2016-10-10 06:38
Great! Works like a charm now. I can now finally get rid of copy pasting special chars from notepad++ (ugly and time consuming workaround)!

Thanks for all the efforts.
