### ISSUE TITLE
Make urls clickable

### ISSUE THREAD

**Issue by T-101** [rpwoodbu/mosh-chrome#117] opened 2016-02-23 09:05 UTC
I use mosh for irc, and as you may know, a lot of urls are shared there. Would be awesome to make them clickable and have them open in chrome itself. Hense this feature request.

I played around in regex and found that this would work nicely for catching urls:
/\s(.*:\/\/([^\s]+))/

**Comment by rpwoodbu** [comment] 2016-02-23 20:08
Duplicate of #52.

**Closed by rpwoodbu** 2016-02-23 20:08 UTC
Labels: duplicate
