### ISSUE TITLE
Mosh client hangs at Loading NaCl module

### ISSUE THREAD

**Issue by halkeye** [rpwoodbu/mosh-chrome#94] opened 2015-05-12 20:16 UTC
I've tried uninstalling and reinstalling the app, restarting the computer, etc etc etc.

hterm_deps.js:168 init: hterm
2015-05-12 13:10:46.992extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.lib.encodeUTF8 (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm_deps.js:4388:26)
    at hterm.Terminal.IO.print.hterm.Terminal.IO.writeUTF16 (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:7787:22)
    at Object.callback (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:117:30)
    at mosh.CommandInstance.run (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:115:23)
    at hterm.Terminal.runCommandClass (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:5256:16)
    at terminal.onTerminalReady (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:40:14)
    at null.<anonymous> (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:4762:37)
    at null.<anonymous> (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:5135:7)
2015-05-12 13:10:47.990mosh_window.html:1 NativeClient: PnaclCoordinator: PNaCl Translator Error: PNaCl ABI verification failed

**Comment by rpwoodbu** [comment] 2015-05-12 20:31
Wow, crazy! What platform are you on? What version is currently installed? Can you repro with the dev release (in the store as "Mosh (dev)")?

**Comment by halkeye** [comment] 2015-05-12 20:37
Windows 7 Enterprise SP 1
Mosh 0.2.10.63
Mosh (dev) 0.2.9.62

Using dev:
hterm_deps.js:168 init: hterm
2015-05-12 13:37:06.524extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.lib.encodeUTF8 (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm/hterm_deps.js:4388:26)
    at hterm.Terminal.IO.print.hterm.Terminal.IO.writeUTF16 (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm/hterm.js:7787:22)
    at Object.callback (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/mosh_window.js:117:30)
    at mosh.CommandInstance.run (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/mosh_window.js:115:23)
    at hterm.Terminal.runCommandClass (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm/hterm.js:5256:16)
    at terminal.onTerminalReady (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/mosh_window.js:40:14)
    at null.<anonymous> (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm/hterm.js:4762:37)
    at null.<anonymous> (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm/hterm.js:5135:7)
2015-05-12 13:37:07.417mosh_window.html:1 NativeClient: PnaclCoordinator: PNaCl Translator Error: PNaCl ABI verification failed

**Comment by halkeye** [comment] 2015-05-12 20:37
Chrome 41.0.2272.101m

**Comment by halkeye** [comment] 2015-05-12 20:40
There's at least one comment on the chrome page hinting other people are getting the same issue.

**Comment by rpwoodbu** [comment] 2015-05-12 20:41
Ah, I think the issue is Chrome 41. The current stable is Chrome 42. I had to update the NaCl SDK to 43 in an attempt to solve Issue #90, and that might have caused an ABI incompatibility with anything older than the current stable Chrome (and I think I recall reading something about that in the changelog).

Please try updating to Chrome 42 and tell me how it goes. If that solves it, then I'll have to close this bug, as I don't have the time to try to support older versions of Chrome.

**Comment by rpwoodbu** [comment] 2015-05-12 20:44
Hmm, the comment on the web store page you mentioned seems to be running Chrome 42, but on ARM. I'm inclined to thing it is a recurrence of Issue #90, and separate from yours. I'll follow up separately with that user. Thanks for bringing it to my attention.

**Comment by halkeye** [comment] 2015-05-12 20:58
aha, 42 does fix it, apparently our corperate firewall or security settings prevents chrome from updating  automatically so I never got 42.

Should I close this?

**Comment by rpwoodbu** [comment] 2015-05-12 21:00
Thanks for testing that. I'll close this issue, thanks. I am sad, though, that my attempt to fix Issue #90 has created collateral damage to users such as yourself. But maybe it is a blessing in disguise; you're better off updating! ;)

**Comment by rpwoodbu** [comment] 2015-05-12 21:26
Note to self: Bump the minimum Chrome version in the manifest to 42.

**Comment by clijunky** [comment] 2015-05-13 01:34
Before you bump the minimum, please be aware that this affects ChromeOS which is only at:
Version 41.0.2272.41 beta (64-bit)
Platform 6680.24.0 (Official Build) beta-channel link
Firmware Google_Link.2695.1.155

I'm going to try updating to bleeding edge Canary to see how that works.

**Comment by halkeye** [comment] 2015-05-13 01:39
My c720 is at:

Version 42.0.2311.134 (64-bit)
Platform 6812.83.0 (Official Build) stable-channel peppy
Firmware Google_Peppy.4389.89.0
Check for and apply updates

**Comment by rpwoodbu** [comment] 2015-05-13 04:18
@clijunky This blog post says that Chrome OS 42 has rolled out to all devices. And the data you provide says beta on it, which means you're actually two versions behind. More to the point, though, setting the minimum version will prevent old browsers such as yours from taking the update, which is strictly better than taking an update that absolutely won't run. It does have the effect of preventing new installs on older browsers, but I'm willing to take that hit; I don't want to go backward with the SDK to support a browser that itself is no longer supported.

**Comment by rpwoodbu** [comment] 2015-05-13 06:05
New release is rolling out now with SHA 699b569.

**Closed by rpwoodbu** 2015-05-13 06:05 UTC
