### ISSUE TITLE
'@' char not supported in password

### ISSUE THREAD

**Issue by snip** [rpwoodbu/mosh-chrome#65] opened 2014-11-16 01:33 UTC
When i'm trying to connect, if i have an @ char in my password it report bad password and do not allow me to connect.

**Comment by rpwoodbu** [comment] 2015-02-02 06:21
This seems to be specific to Windows. I cannot reproduce this on Chrome OS either. I don't have convenient access to a Windows machine, so anyone who does, try this debugging technique:

Using `chrome://extensions`, pull up the `mosh_window.html` once you are at the password prompt. Place a breakpoint in the `sendKeyboard()` function (currently at line 171, subject to change). Inspect the `string` variable (yeah, poor variable name choice on my part) and see what it contains. To be absolutely sure what you're seeing, go to the JS console while it is stopped and type `string.charCodeAt(0)`, and ensure it returns 64. Also note if you see any weird errors or warnings about key codes (I did see hterm complain a bit, but it seemed innocuous).

My best guess is that Windows is sending a [homoglyph](http://en.wikipedia.org/wiki/Homoglyph) of some sort.

I'd also be really interested to know if the problem is reproducible with the [Secure Shell](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo) app, which also uses hterm.

**Comment by snip** [comment] 2015-02-02 10:49
Ok thanks for this. I will try it on my Windows.

For information on OSX i also have this issue with char which are requiring special key combination.
For example "|" char on french keyboard which require Shift+Alt+L doesn't works in mosh-chrome on OSX. Works well in native OSX mosh client.

**Comment by snip** [comment] 2015-02-18 22:20
Hi,

so i've put the breakpoint on line 171:`if (this.running_) {`
With `@`, the function is not triggered.
With `#` it also doesn't print `#` but `string.charCodeAt(0)` return value 27.

(test done after authentication on Windows 7)

Any idea?
Thanks

**Comment by snip** [comment] 2015-02-18 22:30
With  Secure Shell app `@` is printing nothing but `{` and `[` are working without any problem.

**Comment by rpwoodbu** [comment] 2015-03-28 22:55
Sorry for the delay. So if I understand you, this is also happening in the Secure Shell app. That almost certainly means the problem is with `hterm`, the JS terminal emulator that both apps are using. Therefore your best bet is to take it up with the `hterm` folks (which are the same as the Secure Shell folks). Once it is fixed upstream in `hterm`, I can do another build of Mosh for Chrome. In the interim, I'm closing this issue.

**Closed by rpwoodbu** 2015-03-28 22:55 UTC
