### ISSUE TITLE
Tab key changes focus

### ISSUE THREAD

**Issue by leetoburrito** [rpwoodbu/mosh-chrome#89] opened 2015-04-24 16:10 UTC
As of Chrome 43.0.2357.32 beta, the tab key changes focus in the mosh app (instead of passing through to the shell).  CTRL+i works as a workaround, but doesn't help with muscle-memory.

**Comment by rpwoodbu** [comment] 2015-04-24 16:17
Duplicate of Issue #88.

**Closed by rpwoodbu** 2015-04-24 16:17 UTC
Labels: duplicate
