### ISSUE TITLE
Mouse events only work in the top-left corner of mosh window

### ISSUE THREAD

**Issue by colemickens** [rpwoodbu/mosh-chrome#131] opened 2016-09-06 03:55 UTC
(Originally filed in the wrong project: https://github.com/mobile-shell/mosh/issues/803)

If I open vim in mosh and click around, I notice the following:

1. Everything works fine in the top-left corner of the window.

2. Click and scroll events elsewhere are translated into key presses.

I've noticed this in both Dev/Stable in both Windows and ChromeOS, as well as Dev/OS X.

Here's a video of this buggy behavior: https://www.youtube.com/watch?v=BypvSmJOQCc

**Comment by rpwoodbu** [comment] 2016-09-06 04:09
Interesting. I don't know much about mouse support in Mosh TBH, but I'll take a swing at this.

Thanks so much for the helpful video; I was able to reproduce this easily after watching that. I tried reproducing in Secure Shell (which shares the same hterm terminal emulator), and it seems to work fine there. I also tried reproducing with the upstream Mosh directly (albeit via an ssh session), and it worked fine. So I suspect that hterm had a bug which has been fixed upstream. It is also possible that I'm holding hterm wrong, but I can't imagine how.

The first thing to do, then, will be for me to upgrade to the latest stable hterm, and see how it goes.

**Comment by cgull** [comment] 2016-09-06 18:28
I rewrote the mouse support in Mosh a year back, I know far too much about it :)

There's 3 or 4 different modes for mouse reporting encoding available in modern terminals that have gotten added over time.  They differ in how the x/y position values are encoded.  The earliest version just encodes the position report bytes as ASCII printable characters.  That only works for screens < 96 rows/columns.  Another (the 'urxvt' scheme) seems to be a variant of this.  Another encodes the values as UTF-8 codepoints.  The last and best sends x/y in printable ASCII integers and can handle arbitrary screen sizes.

Your video seems to suggest that hterm is sending position reports in one of the older encodings, but mosh-client, or possibly vim at the far end, is expecting reports in another encoding.  My guess is that hterm is sending in UTF-8 mode and the recipient is expecting ASCII-byte mode.

Mosh's handling of the encoding modes, and the flags for the reporting modes, is a little hinky and definitely doesn't work the way these features are specified.  It happens to work for most apps and most terminals most of the time, if they send simple modesets in a fairly reasonable sequence.  It's entirely possible that this is a mosh or hterm issue that only shows up with this specific combo of components though.

If this turns out to be a Mosh problem, bug me or reopen https://github.com/mobile-shell/mosh/issues/803 and we'll try and get this sorted out.

**Comment by rpwoodbu** [comment] 2016-09-11 03:50
I upgraded from hterm 1.54 to 1.57, but that did not fix the issue. I did some debugging, and I can see that it is outputting in the first mode @cgull describes. And looking at the hterm code, I can see that this is the only mode supported. So while 96 rows/columns would be the "expected" limit, hterm is clamping not at 0x7f, but at 0xff, making the limit 224. This _works_ with Secure Shell and vim. And this works with Secure Shell -> mosh -> vim. So it would appear the high-order characters are getting clobbered somewhere in my code. Debugging continues.

**Comment by rpwoodbu** [comment] 2016-09-11 05:18
The issue was that these large characters got UTF-8 encoded on their way to NaCl from JS. More details in the commit I'm about to push. This fix will be in the next dev release, which I hope to do soon (I have one more thing I want to fix first).

**Closed** 2016-09-11 05:21 UTC

**Comment by rpwoodbu** [comment] 2016-09-12 03:04
v0.3.7 is rolling out now to the dev track. Let me know if there are further issues.

**Comment by colemickens** [comment] 2016-09-13 01:11
This is working for me on every platform, thanks for the fast turn around!
